[package]
name = "hyperlight-fuzz"
version = "0.0.0"
publish = false
edition = { workspace = true }

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
hyperlight-testing = { workspace = true }
hyperlight-host = { workspace = true, default-features = true, features = ["fuzzing"]}
hyperlight-common = {workspace = true}

[[bin]]
name = "fuzz_guest_estimate_trace_event"
path = "fuzz_targets/guest_estimate_trace_event.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_guest_call"
path = "fuzz_targets/guest_call.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_guest_trace"
path = "fuzz_targets/guest_trace.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_host_call"
path = "fuzz_targets/host_call.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_host_print"
path = "fuzz_targets/host_print.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_virtq_packed_ring"
path = "fuzz_targets/virtq_packed_ring.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_push_pop_buffer"
path = "fuzz_targets/fuzz_push_pop_buffer.rs"
test = false
doc = false
bench = false

[features]
default = []
trace = ["hyperlight-host/trace_guest", "hyperlight-common/trace_guest"]
